#!/usr/bin/env bash
# This is the maintainence launcher for the snap, make necessary runtime environment changes to make the snap work here.  You may also insert security confinement/deprecation/obsoletion notice of the snap here.

set \
	-o errexit \
	-o errtrace \
	-o nounset \
	-o pipefail

# Interface connection detection #
if ! ls /etc/sensors.d &>/dev/null; then
    zenity \
        --warning \
        --text="It seems that this snap isn't connected to the <tt>hardware-observe</tt> security confinement interface.  The application requires this access and as a result some functionalities may not work(including but not limited to, the H264 Controls tab.\n\nYou can connect this interface by running the following command in a terminal:\\n\\n    sudo snap connect ${SNAP_NAME}:hardware-observe\\n\\n" \
        --width=600
fi

if ! ls /media &>/dev/null; then
    zenity \
        --info \
        --text="It seems that this snap isn't connected to the <tt>removable-media</tt> security confinement interface.  If you want to save the recordings under <tt>/media</tt>, <tt>/run/media</tt>, or <tt>/mnt</tt> you may want to connect this interface by running the following command in a terminal:\\n\\n    sudo snap connect ${SNAP_NAME}:removable-media\\n\\n" \
        --width=600
fi

# Finally run the next part of the command chain
exec "${@}"
